// ═══════════════════════════════════════════
//  レシピDB — 自作テンプレート（著作権フリー）
//  家庭料理の定番20品、汎用名詞・ざっくり分量
// ═══════════════════════════════════════════

export interface Ingredient {
  name: string;
  amount: number;
  unit: string;       // g | ml | 個 | 本 | 枚 | 袋 | 丁 | 合 | 玉 | 切れ | 杯
  category: string;   // meat | vegetable | dairy | grain | other
}

export interface Recipe {
  id: string;
  name: string;
  description: string;
  genre: "和" | "洋" | "中" | "その他";
  mealType: string[];  // breakfast | lunch | dinner | snack
  time: number;        // minutes
  difficulty: "簡単" | "普通" | "本格的";
  baseServings: number;
  ingredients: Ingredient[];
  seasonings: string[];  // assumed available
  steps: string[];
}

export const recipes: Recipe[] = [
  {
    id: "chicken_curry",
    name: "チキンカレー",
    description: "ゴロゴロ野菜と鶏肉の定番カレー",
    genre: "洋",
    mealType: ["lunch", "dinner"],
    time: 40,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "鶏もも肉", amount: 300, unit: "g", category: "meat" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "にんじん", amount: 1, unit: "本", category: "vegetable" },
      { name: "じゃがいも", amount: 2, unit: "個", category: "vegetable" },
      { name: "カレールー", amount: 4, unit: "個", category: "other" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
    ],
    seasonings: ["サラダ油", "水"],
    steps: [
      "鶏もも肉を一口大、野菜を食べやすい大きさに切る",
      "鍋に油を熱し、鶏肉を炒めて表面に焼き色をつける",
      "玉ねぎ・にんじん・じゃがいもを加えて炒める",
      "水500mlを加え、沸騰したらアクを取り中火で15分煮る",
      "火を止めてカレールーを溶かし、とろみがつくまで弱火で5分煮る",
      "炊いたご飯と一緒に盛り付ける",
    ],
  },
  {
    id: "nikujaga",
    name: "肉じゃが",
    description: "ほっこり甘辛い定番の煮物",
    genre: "和",
    mealType: ["dinner"],
    time: 35,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "豚薄切り肉", amount: 200, unit: "g", category: "meat" },
      { name: "じゃがいも", amount: 3, unit: "個", category: "vegetable" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "にんじん", amount: 1, unit: "本", category: "vegetable" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "料理酒", "サラダ油", "水"],
    steps: [
      "じゃがいもは皮をむいて一口大、玉ねぎはくし切り、にんじんは乱切りにする",
      "鍋に油を熱し、豚肉を炒めて色が変わったら野菜を加える",
      "水300ml・醤油大さじ2・みりん大さじ2・砂糖大さじ1・酒大さじ1を加える",
      "落とし蓋をして中火で20分、じゃがいもが柔らかくなるまで煮る",
      "味が染みるように5分置いてから盛り付ける",
    ],
  },
  {
    id: "oyakodon",
    name: "親子丼",
    description: "ふわとろ卵と鶏肉の丼もの",
    genre: "和",
    mealType: ["lunch", "dinner"],
    time: 20,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "鶏もも肉", amount: 250, unit: "g", category: "meat" },
      { name: "卵", amount: 3, unit: "個", category: "dairy" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "だし"],
    steps: [
      "鶏もも肉を一口大に切り、玉ねぎを薄切りにする",
      "フライパンに水150ml・醤油大さじ2・みりん大さじ2・砂糖小さじ1を煮立てる",
      "玉ねぎと鶏肉を入れ、中火で5分煮る",
      "溶き卵の2/3を回し入れ蓋をして1分、残りを加えて30秒で火を止める",
      "丼にご飯を盛り、上にのせる",
    ],
  },
  {
    id: "shogayaki",
    name: "豚の生姜焼き",
    description: "ご飯がすすむ甘辛ダレの定番おかず",
    genre: "和",
    mealType: ["lunch", "dinner"],
    time: 15,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "豚ロース肉", amount: 300, unit: "g", category: "meat" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "キャベツ", amount: 3, unit: "枚", category: "vegetable" },
    ],
    seasonings: ["醤油", "みりん", "料理酒", "生姜", "サラダ油"],
    steps: [
      "豚ロースに軽く筋切りし、玉ねぎを薄切り、キャベツを千切りにする",
      "醤油大さじ2・みりん大さじ1・酒大さじ1・おろし生姜小さじ1を混ぜる",
      "フライパンに油を熱し、豚肉を両面焼いて玉ねぎを加える",
      "合わせ調味料を回しかけ、絡めながら炒める",
      "皿にキャベツを敷き、肉を盛り付ける",
    ],
  },
  {
    id: "yasai_itame",
    name: "野菜炒め",
    description: "シャキシャキ食感の手軽な一品",
    genre: "中",
    mealType: ["lunch", "dinner"],
    time: 10,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "豚薄切り肉", amount: 150, unit: "g", category: "meat" },
      { name: "キャベツ", amount: 4, unit: "枚", category: "vegetable" },
      { name: "にんじん", amount: 0.5, unit: "本", category: "vegetable" },
      { name: "もやし", amount: 1, unit: "袋", category: "vegetable" },
    ],
    seasonings: ["塩", "胡椒", "醤油", "サラダ油"],
    steps: [
      "キャベツはざく切り、にんじんは短冊切り、肉は食べやすく切る",
      "フライパンに油を強火で熱し、肉を炒める",
      "にんじん→キャベツ→もやしの順に加えて手早く炒める",
      "塩・胡椒・醤油少々で味を調える",
    ],
  },
  {
    id: "chahan",
    name: "チャーハン",
    description: "パラパラ仕上げの基本チャーハン",
    genre: "中",
    mealType: ["lunch"],
    time: 10,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "米", amount: 2, unit: "合", category: "grain" },
      { name: "卵", amount: 2, unit: "個", category: "dairy" },
      { name: "長ねぎ", amount: 1, unit: "本", category: "vegetable" },
      { name: "ハム", amount: 4, unit: "枚", category: "meat" },
    ],
    seasonings: ["塩", "胡椒", "醤油", "サラダ油", "ごま油"],
    steps: [
      "長ねぎをみじん切り、ハムを1cm角に切る",
      "フライパンに油を強火で熱し、溶き卵を入れて素早くかき混ぜる",
      "半熟のうちにご飯を加え、切るように炒める",
      "ハム・ねぎを加え、塩・胡椒・醤油で味つけ、仕上げにごま油",
    ],
  },
  {
    id: "teriyaki_chicken",
    name: "鶏の照り焼き",
    description: "つやつやタレが食欲をそそる",
    genre: "和",
    mealType: ["lunch", "dinner"],
    time: 20,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "鶏もも肉", amount: 300, unit: "g", category: "meat" },
      { name: "長ねぎ", amount: 1, unit: "本", category: "vegetable" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "料理酒", "サラダ油"],
    steps: [
      "鶏もも肉の厚い部分を開いて均一にし、長ねぎを4cm幅に切る",
      "フライパンに油を熱し、鶏肉を皮目から中火で5分焼く",
      "裏返して長ねぎも加え、蓋をして4分蒸し焼き",
      "醤油大さじ2・みりん大さじ2・砂糖大さじ1・酒大さじ1を加え煮絡める",
      "食べやすく切って盛り付ける",
    ],
  },
  {
    id: "potato_salad",
    name: "ポテトサラダ",
    description: "ホクホクじゃがいもの定番サラダ",
    genre: "洋",
    mealType: ["lunch", "dinner"],
    time: 25,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "じゃがいも", amount: 3, unit: "個", category: "vegetable" },
      { name: "きゅうり", amount: 1, unit: "本", category: "vegetable" },
      { name: "ハム", amount: 3, unit: "枚", category: "meat" },
      { name: "卵", amount: 1, unit: "個", category: "dairy" },
    ],
    seasonings: ["マヨネーズ", "塩", "胡椒", "酢"],
    steps: [
      "じゃがいもを茹でて皮をむき、熱いうちにつぶす",
      "卵を茹でて粗みじん切り、きゅうりは薄切りにして塩もみ",
      "ハムを短冊切りにする",
      "じゃがいもに全ての具材を加え、マヨネーズ大さじ3・塩・胡椒で和える",
    ],
  },
  {
    id: "omurice",
    name: "オムライス",
    description: "ケチャップライスをふわふわ卵で包む",
    genre: "洋",
    mealType: ["lunch", "dinner"],
    time: 25,
    difficulty: "普通",
    baseServings: 2,
    ingredients: [
      { name: "卵", amount: 4, unit: "個", category: "dairy" },
      { name: "鶏もも肉", amount: 150, unit: "g", category: "meat" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
      { name: "ケチャップ", amount: 60, unit: "ml", category: "other" },
    ],
    seasonings: ["塩", "胡椒", "バター", "サラダ油"],
    steps: [
      "鶏肉を1cm角、玉ねぎをみじん切りにする",
      "フライパンで鶏肉と玉ねぎを炒め、ご飯を加える",
      "ケチャップ大さじ4を加えて全体に絡め、皿に盛る",
      "別のフライパンにバターを溶かし、溶き卵を流して半熟のオムレツを作る",
      "ケチャップライスの上にのせ、ケチャップをかける",
    ],
  },
  {
    id: "yakisoba",
    name: "焼きそば",
    description: "ソース香る鉄板の味",
    genre: "その他",
    mealType: ["lunch"],
    time: 15,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "焼きそば麺", amount: 2, unit: "玉", category: "grain" },
      { name: "豚薄切り肉", amount: 100, unit: "g", category: "meat" },
      { name: "キャベツ", amount: 3, unit: "枚", category: "vegetable" },
      { name: "もやし", amount: 0.5, unit: "袋", category: "vegetable" },
    ],
    seasonings: ["中濃ソース", "塩", "胡椒", "サラダ油"],
    steps: [
      "キャベツをざく切り、豚肉を食べやすい大きさに切る",
      "フライパンに油を熱し、豚肉→キャベツ→もやしの順に炒める",
      "麺を加えて水少々をふり、ほぐしながら炒める",
      "ソース大さじ3を回しかけ、全体に絡める",
    ],
  },
  {
    id: "mapo_tofu",
    name: "麻婆豆腐",
    description: "ピリ辛あんかけのご飯のお供",
    genre: "中",
    mealType: ["dinner"],
    time: 20,
    difficulty: "普通",
    baseServings: 2,
    ingredients: [
      { name: "豚ひき肉", amount: 200, unit: "g", category: "meat" },
      { name: "豆腐", amount: 1, unit: "丁", category: "other" },
      { name: "長ねぎ", amount: 0.5, unit: "本", category: "vegetable" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
    ],
    seasonings: ["醤油", "味噌", "豆板醤", "片栗粉", "ごま油", "生姜", "にんにく"],
    steps: [
      "豆腐を2cm角に切って湯通し、長ねぎをみじん切りにする",
      "フライパンにごま油を熱し、ひき肉をしっかり炒める",
      "豆板醤小さじ1・おろし生姜・にんにくを加えて香りを出す",
      "水150ml・醤油大さじ1・味噌大さじ1を加え、豆腐を入れて3分煮る",
      "水溶き片栗粉でとろみをつける",
    ],
  },
  {
    id: "hamburg",
    name: "ハンバーグ",
    description: "肉汁たっぷりの手作りハンバーグ",
    genre: "洋",
    mealType: ["dinner"],
    time: 30,
    difficulty: "普通",
    baseServings: 2,
    ingredients: [
      { name: "合いびき肉", amount: 300, unit: "g", category: "meat" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "卵", amount: 1, unit: "個", category: "dairy" },
      { name: "パン粉", amount: 30, unit: "g", category: "grain" },
    ],
    seasonings: ["塩", "胡椒", "ナツメグ", "ケチャップ", "中濃ソース", "サラダ油"],
    steps: [
      "玉ねぎをみじん切りにし、飴色になるまで炒めて冷ます",
      "ひき肉・玉ねぎ・卵・パン粉・塩・胡椒・ナツメグを粘りが出るまで混ぜる",
      "2等分にして小判型に成形し、中央をくぼませる",
      "フライパンに油を熱し、強火で両面に焼き色をつけ、蓋をして弱火で8分蒸し焼き",
      "ケチャップ大さじ2・ソース大さじ1を混ぜてかける",
    ],
  },
  {
    id: "chikuzenni",
    name: "筑前煮",
    description: "根菜たっぷりの懐かしい煮物",
    genre: "和",
    mealType: ["dinner"],
    time: 40,
    difficulty: "普通",
    baseServings: 2,
    ingredients: [
      { name: "鶏もも肉", amount: 200, unit: "g", category: "meat" },
      { name: "にんじん", amount: 1, unit: "本", category: "vegetable" },
      { name: "れんこん", amount: 150, unit: "g", category: "vegetable" },
      { name: "こんにゃく", amount: 1, unit: "枚", category: "other" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "料理酒", "だし", "サラダ油"],
    steps: [
      "鶏肉は一口大、にんじん・れんこんは乱切り、こんにゃくは手でちぎって下茹で",
      "鍋に油を熱し、鶏肉を炒めて野菜・こんにゃくを加える",
      "だし300ml・醤油大さじ2・みりん大さじ2・砂糖大さじ1・酒大さじ1を加える",
      "落とし蓋をして中火で20分、煮汁が少なくなるまで煮る",
    ],
  },
  {
    id: "soboro_don",
    name: "そぼろ丼",
    description: "甘辛そぼろと炒り卵の二色丼",
    genre: "和",
    mealType: ["lunch", "dinner"],
    time: 15,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "鶏ひき肉", amount: 200, unit: "g", category: "meat" },
      { name: "卵", amount: 2, unit: "個", category: "dairy" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "生姜", "サラダ油"],
    steps: [
      "フライパンにひき肉・醤油大さじ2・みりん大さじ1・砂糖大さじ1・おろし生姜を入れ、箸4本でかき混ぜながら火を通す",
      "別のフライパンに油をひき、溶き卵に砂糖少々を加えて炒り卵を作る",
      "丼にご飯を盛り、そぼろと炒り卵を半分ずつのせる",
    ],
  },
  {
    id: "napolitan",
    name: "ナポリタン",
    description: "喫茶店風の懐かしいケチャップパスタ",
    genre: "洋",
    mealType: ["lunch"],
    time: 20,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "スパゲティ", amount: 200, unit: "g", category: "grain" },
      { name: "玉ねぎ", amount: 1, unit: "個", category: "vegetable" },
      { name: "ピーマン", amount: 2, unit: "個", category: "vegetable" },
      { name: "ウインナー", amount: 4, unit: "本", category: "meat" },
      { name: "ケチャップ", amount: 80, unit: "ml", category: "other" },
    ],
    seasonings: ["塩", "胡椒", "バター", "サラダ油"],
    steps: [
      "スパゲティを表示通り茹でる",
      "玉ねぎは薄切り、ピーマンは輪切り、ウインナーは斜め切り",
      "フライパンにバターと油で玉ねぎ・ウインナーを炒め、ピーマンを加える",
      "茹でたパスタを加え、ケチャップ大さじ5を絡めて炒める",
      "塩・胡椒で味を調える",
    ],
  },
  {
    id: "misoshiru",
    name: "具だくさん味噌汁",
    description: "野菜たっぷりで栄養満点",
    genre: "和",
    mealType: ["breakfast", "lunch", "dinner"],
    time: 15,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "豆腐", amount: 0.5, unit: "丁", category: "other" },
      { name: "長ねぎ", amount: 0.5, unit: "本", category: "vegetable" },
      { name: "わかめ", amount: 5, unit: "g", category: "other" },
    ],
    seasonings: ["味噌", "だし"],
    steps: [
      "豆腐を1.5cm角に切り、長ねぎは小口切りにする",
      "鍋に水400mlとだしを入れて沸かす",
      "豆腐・わかめを加えて1分煮る",
      "火を止めて味噌大さじ2を溶かし入れ、ねぎを散らす",
    ],
  },
  {
    id: "tamagoyaki",
    name: "だし巻き卵",
    description: "ふんわりジューシーな卵焼き",
    genre: "和",
    mealType: ["breakfast", "lunch"],
    time: 10,
    difficulty: "普通",
    baseServings: 2,
    ingredients: [
      { name: "卵", amount: 3, unit: "個", category: "dairy" },
    ],
    seasonings: ["だし", "砂糖", "醤油", "塩", "サラダ油"],
    steps: [
      "卵を溶き、だし大さじ2・砂糖小さじ1・醤油少々・塩少々を加える",
      "卵焼き器に油をひいて中火で熱する",
      "卵液を1/3ずつ流し、巻きながら3回に分けて焼く",
      "まきすで形を整え、切り分ける",
    ],
  },
  {
    id: "kinpira_gobo",
    name: "きんぴらごぼう",
    description: "甘辛味でご飯に合う常備菜",
    genre: "和",
    mealType: ["lunch", "dinner"],
    time: 15,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "ごぼう", amount: 1, unit: "本", category: "vegetable" },
      { name: "にんじん", amount: 0.5, unit: "本", category: "vegetable" },
    ],
    seasonings: ["醤油", "みりん", "砂糖", "ごま油", "唐辛子", "白ごま"],
    steps: [
      "ごぼうは皮をこそぎ、細切りにして水にさらす。にんじんも細切り",
      "フライパンにごま油を熱し、ごぼう→にんじんの順に炒める",
      "醤油大さじ1.5・みりん大さじ1・砂糖小さじ1を加えて汁気がなくなるまで炒める",
      "白ごまをふる",
    ],
  },
  {
    id: "tonjiru",
    name: "豚汁",
    description: "具材ゴロゴロのご馳走汁物",
    genre: "和",
    mealType: ["dinner"],
    time: 25,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "豚薄切り肉", amount: 100, unit: "g", category: "meat" },
      { name: "大根", amount: 150, unit: "g", category: "vegetable" },
      { name: "にんじん", amount: 0.5, unit: "本", category: "vegetable" },
      { name: "長ねぎ", amount: 0.5, unit: "本", category: "vegetable" },
      { name: "豆腐", amount: 0.5, unit: "丁", category: "other" },
    ],
    seasonings: ["味噌", "だし", "ごま油"],
    steps: [
      "大根・にんじんはいちょう切り、長ねぎは小口切り、豆腐はさいの目に切る",
      "鍋にごま油を熱し、豚肉を炒めて大根・にんじんを加える",
      "水500mlとだしを加え、野菜が柔らかくなるまで10分煮る",
      "豆腐を加えて2分煮、火を止めて味噌大さじ2.5を溶かし入れる",
      "器に盛り、ねぎを散らす",
    ],
  },
  {
    id: "sake_shioyaki",
    name: "鮭の塩焼き定食",
    description: "シンプルだけど間違いない和定食",
    genre: "和",
    mealType: ["breakfast", "dinner"],
    time: 20,
    difficulty: "簡単",
    baseServings: 2,
    ingredients: [
      { name: "鮭", amount: 2, unit: "切れ", category: "meat" },
      { name: "大根", amount: 100, unit: "g", category: "vegetable" },
      { name: "米", amount: 2, unit: "合", category: "grain" },
    ],
    seasonings: ["塩", "醤油"],
    steps: [
      "鮭に塩をふって10分おき、出てきた水気を拭く",
      "グリルまたはフライパンで中火で両面を焼く（片面5分ずつ）",
      "大根をすりおろす",
      "ご飯・鮭・大根おろしを盛り付け、醤油を添える",
    ],
  },
];

// Named export: import { recipes } from "./recipes"
